# paths to ignore
ignore:
  - "docs/**/*"
  - "build_tools/**/*"
  - "examples/*"
  - ".github/*"
  - ".binder/*"
  - "enhancement_proposals/*"
  - "*.md"
  - "*.yml"
  - "*.yaml"

# PR status check
coverage:
  status:
    project:
      default:
        # threshold: 1%
        informational: true
    patch:
      default:
        informational: true
