name: Test

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
    types: [opened, synchronize]

  # Allows workflows to be manually triggered
  workflow_dispatch:

permissions:
  contents: read
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Look into replacing this with pre-commit.ci
  code-quality:
    name: code-quality
    runs-on: ubuntu-latest
    steps:
      - name: repository checkout step
        uses: actions/checkout@v4
      - name: python environment step
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: install pre-commit
        run: python3 -m pip install pre-commit
      - id: changed-files
        name: identify modified files
        uses: tj-actions/changed-files@v45
      - name: run pre-commit hooks on modified files
        run: pre-commit run --color always --files ${{ steps.changed-files.outputs.all_changed_files }} --show-diff-on-failure
      - name: check missing __init__ files
        run: build_tools/fail_on_missing_init_files.sh
        shell: bash

  test-nodevdeps:
    needs: code-quality
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install skbase and dependencies
        run: |
          python -m pip install .

      - name: Run pytest-free tests
        run: |
          python skbase/_nopytest_tests.py

  test-full:
    needs: code-quality
    name: Test ${{ matrix.os }}-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest, macOS-latest, windows-latest]
          python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install .[test] --no-cache-dir

      - name: Show dependencies
        run: python -m pip list

      - name: Run tests
        run: |
          python -m pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
